/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/AddLibraryScreen` | `/AddLibraryScreen`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/BookDetailsScreen` | `/BookDetailsScreen`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/BooksTab` | `/BooksTab`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/HomeScreen` | `/HomeScreen`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/LibraryView` | `/LibraryView`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/my_libraries` | `/my_libraries`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/ProfileScreen` | `/ProfileScreen`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/SavedTab` | `/SavedTab`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/SignInScreen` | `/SignInScreen`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/SignUp` | `/SignUp`; params?: Router.UnknownInputParams; } | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/AddLibraryScreen` | `/AddLibraryScreen`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/BookDetailsScreen` | `/BookDetailsScreen`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/BooksTab` | `/BooksTab`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/HomeScreen` | `/HomeScreen`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/LibraryView` | `/LibraryView`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/my_libraries` | `/my_libraries`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/ProfileScreen` | `/ProfileScreen`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/SavedTab` | `/SavedTab`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/SignInScreen` | `/SignInScreen`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/SignUp` | `/SignUp`; params?: Router.UnknownOutputParams; } | { pathname: `/+not-found`, params: Router.UnknownOutputParams & {  } };
      href: Router.RelativePathString | Router.ExternalPathString | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/AddLibraryScreen${`?${string}` | `#${string}` | ''}` | `/AddLibraryScreen${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/BookDetailsScreen${`?${string}` | `#${string}` | ''}` | `/BookDetailsScreen${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/BooksTab${`?${string}` | `#${string}` | ''}` | `/BooksTab${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/HomeScreen${`?${string}` | `#${string}` | ''}` | `/HomeScreen${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/LibraryView${`?${string}` | `#${string}` | ''}` | `/LibraryView${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/my_libraries${`?${string}` | `#${string}` | ''}` | `/my_libraries${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/ProfileScreen${`?${string}` | `#${string}` | ''}` | `/ProfileScreen${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/SavedTab${`?${string}` | `#${string}` | ''}` | `/SavedTab${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/SignInScreen${`?${string}` | `#${string}` | ''}` | `/SignInScreen${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/SignUp${`?${string}` | `#${string}` | ''}` | `/SignUp${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/AddLibraryScreen` | `/AddLibraryScreen`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/BookDetailsScreen` | `/BookDetailsScreen`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/BooksTab` | `/BooksTab`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/HomeScreen` | `/HomeScreen`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/LibraryView` | `/LibraryView`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/my_libraries` | `/my_libraries`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/ProfileScreen` | `/ProfileScreen`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/SavedTab` | `/SavedTab`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/SignInScreen` | `/SignInScreen`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/SignUp` | `/SignUp`; params?: Router.UnknownInputParams; } | `/+not-found` | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
    }
  }
}
